[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5"
chrono = "0.4.19"
config = "0.13"
env_logger = "0.9"
hyper = "0.14"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
tower-http = { version = "0.3", features = ["trace"] }
uuid = { version = "0.8", features = ["v4"] }

[dependencies.sqlx]
version = "0.5.13"
default-features = false
features = [
"runtime-tokio-rustls",
"macros",
"postgres",
"uuid",
"chrono",
"migrate"
]

[dependencies.tokio]
version = "1.18"
features = ["macros", "rt-multi-thread"]
